[tool.ruff]
# 実行するルール
select = ["E", "F", "I", "W"]
# 行の長さ
line-length = 100
# ソートの対象
src = ["src", "tests"]
# importのソート
[tool.ruff.isort]
known-first-party = ["app"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"
